# Generated by Django 2.1.15 on 2020-06-15 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_uservisitedreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservisitedreview',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_time', to='movies.Movie'),
        ),
    ]
