# Generated by Django 2.1.15 on 2020-06-15 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20200615_1648'),
        ('accounts', '0009_auto_20200615_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uservisitedreview',
            name='movie',
        ),
        migrations.AddField(
            model_name='uservisitedreview',
            name='review',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='movies.Review'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uservisitedreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
