# Generated by Django 2.1.15 on 2020-06-14 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20200614_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='review',
        ),
    ]
