# Generated by Django 2.1.15 on 2020-06-14 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_reply_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='repNationNm',
            field=models.ManyToManyField(related_name='repNationNm_movie', to='movies.RepNationNm'),
        ),
    ]
