# Generated by Django 2.1.15 on 2020-06-14 01:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0005_auto_20200614_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user_hit_time',
            field=models.ManyToManyField(related_name='hit_time_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
