# Generated by Django 2.1.15 on 2020-06-15 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_review_user_hit_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moviehistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_history', to='movies.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Reviewhistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_history', to='movies.Review')),
            ],
        ),
    ]
