# Generated by Django 2.1.15 on 2020-06-15 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_moviehistory_reviewhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviehistory',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie'),
        ),
        migrations.AlterField(
            model_name='reviewhistory',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Review'),
        ),
    ]
