# Generated by Django 2.1.15 on 2020-06-16 04:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0008_auto_20200615_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='unlike_users',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='unlike_users',
        ),
        migrations.RemoveField(
            model_name='review',
            name='unlike_users',
        ),
        migrations.AddField(
            model_name='comment',
            name='dislike_users',
            field=models.ManyToManyField(related_name='dislike_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reply',
            name='dislike_users',
            field=models.ManyToManyField(related_name='dislike_reply', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='dislike_users',
            field=models.ManyToManyField(related_name='dislike_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
