# Generated by Django 2.1.15 on 2020-06-17 04:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20200616_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='like_users',
            field=models.ManyToManyField(null=True, related_name='like_movies', to=settings.AUTH_USER_MODEL),
        ),
    ]
